### ISSUE TITLE
Include essential-launcher in F-Droid

### ISSUE THREAD

**Issue by clemensbartz** [clemensbartz/essential-launcher#10]
Copied from #9, taken from @IzzySoft:

> If you want to, we could also bring your launcher into the official F-Droid repo; as far as I can see, it meets all their inclusion criteria. If you'd like that, let me know if you need assistance (I could file the "Request For Packaging" (RFP) for you. As F-Droid usually signs packages with their own key, other than with my repo cross-updates would not be possible – but on demand, they also offer "reproducible builds" (i.e. they build from your sources and compare the result with the .apk you provide; if the two match, your .apk is taken, so cross-updates are possible); so we should include with the RFP if you want that.

Link to the request: https://gitlab.com/fdroid/rfp/issues/448

**Comment by IzzySoft** [comment]
OK then: [here you go](https://gitlab.com/fdroid/rfp/issues/448). Be welcome to add your bit in a comment there (e.g. on reproducible builds, as pointed out).

**Comment by clemensbartz** [comment]
@IzzySoft Thank you very much. I have added a few comments (not sure if that was correct).

**Comment by IzzySoft** [comment]
Sure it was, thanks! I've left a comment for the maintainers that you're the dev (though they could find out following the link to this issue here). It's always a good sign if the developer takes part in the RFP as that signals active support to the maintainers. So another :+1:

**Comment by clemensbartz** [comment]
F-Droid request has been merged into repository. Waiting for app to arrive in global repository.

**Comment by clemensbartz** [comment]
Build is currently failing in F-Droid: https://f-droid.org/wiki/page/de.clemensbartz.android.launcher

**Comment by IzzySoft** [comment]
And the "backlog" is quite huge with the recent build server issues :scream:

**Comment by clemensbartz** [comment]
@IzzySoft: Do I need to manually trigger a new build somewhere? It seems that a rebuild was not triggered.

**Comment by IzzySoft** [comment]
@clemensbartz not that I know of. But I neither can tell what will cause a rebuild to be started once it failed. A new release might do that (with the build issues hopefully fixed).

**Comment by clemensbartz** [comment]
App has been rebuilt. Added badges on website.
