### ISSUE TITLE
Ability to hide apps (feature request)

### ISSUE THREAD

**Issue by esmoak** [clemensbartz/essential-launcher#37]
If this could be done while maintaining the small app size:

1) Long press the app and have the option to hide it.

2) Long press the app drawer and have the option to toggle on/off hidden apps (located near the widget options).

Purpose would be to clean up the app drawer without uninstalling certain apps.

Thanks.

**Comment by clemensbartz** [comment]
I just did a little experiment regarding this. From my point of view, this is possible and, at the moment, will be implemented like you requested:

- add new column "hidden" to the database
- add new context menu item "Hide in drawer" to the app drawer
- add new context menu item with toggle for app drawer "Show hidden apps in drawer"

**Comment by clemensbartz** [comment]
Postponed to release 1.6
