### ISSUE TITLE
Manually ordering applications on the dock

### ISSUE THREAD

**Issue by SimplyMiles** [clemensbartz/essential-launcher#38]
I really like the launcher, but a minor annoyance I've come across is the inability to choose which app is in which position on the dock. Stickying apps seems to put them in a fixed order, and a change I'd suggest would be making stickying an app put it before or after the last app opposed to the way it's done now. If there's already a way to order apps I apologize but I haven't found it. 

Thanks for creating such a simple and functional launcher.

**Comment by clemensbartz** [comment]
Thank you for reaching out. Apps in the dock are ordered by usage. If you are using an app more often, it will get promoted further to the left (for left-to-right readers) or right (for right-to-left-readers).

Pinning apps will create another category "in front" of the regular apps with the same behavior.

The sorting factors are (in the order of release [1.4](https://github.com/clemensbartz/essential-launcher/blob/4dde3397d2c7ab41e33e4ebec5d0392d359dd199/launcher/src/main/java/de/clemensbartz/android/launcher/models/HomeModel.java#L64)):
- sticky
- usage
- package name of the app
- class name of the app

I experimented a few times with adding weights as an addition. That would have required additional UI and coding making the app heavier. I also thought that it is intransparent for the user if there was no dedicated view to look out for.

So as of now, there will not be any feature regarding dedicated ordering. I would ask you to launch the apps a few times for the ordering to happen, but, of course, if you have an app that you use the most, this will not be a permanent solution.

**Comment by SimplyMiles** [comment]
Thanks for the clarification, it does make a lot more sense now that you explain it that way. I decided to use an auto tapping app to greatly inflate the number of opens so that the apps will always be in their position.
