### ISSUE TITLE
widget size can't be chaged

### ISSUE THREAD

**Issue by JRapsky** [clemensbartz/essential-launcher#42]
### General Information

  * Essential Launcher Version:  latest
  * Android Version:  CM13 
  * Device with manufacturer: Bluboo Maya Max
  * RAM:  3GB
  * App installed from: F-Droid
  
### Actual behavior

I want to use the CM cLock widget for weather preview and agenda. Unfortunately it is not possible to resize the widget. So I see the clock, but no weather or agenda.

### Expected behavior

a long tap on the widget should give the option to resize it on the grid

**Comment by clemensbartz** [comment]
Thank you for your suggestion. Essential Launcher does not implement a grid.

However, in issue #31 I have implemented a basic resizing and moving algorithm.
