### ISSUE TITLE
widget alternative

### ISSUE THREAD

**Issue by JRapsky** [clemensbartz/essential-launcher#44]
### General Information

  * Essential Launcher Version: 1.4
  * Android Version:  CM13
  * Device with manufacturer: Bluboo Maya Max
  * RAM: 3GB
  * App installed from: F-Droid
  
### Actual behavior

supports only one widget, resizing of widget will come with the next release

### Expected behavior

Could you add essential widget for weather and agenda to the launcher, maybe as card or panel? Bad exampel, because of the size, ASAP Launcher. Good example is SickSky launcher, unfortunately not longer maintained.

Otherwise every next widget could cause new issues to your project. Would be great to see, if you can do this in minimal size.

**Comment by clemensbartz** [comment]
There will never be any built-in widget(s) in Essential Launcher. This should be a different project, but I will not develop that as widgets are not nice in Android.
