### ISSUE TITLE
Enhancement - option to swipe up to reveal the app drawer

### ISSUE THREAD

**Issue by Zuccace** [clemensbartz/essential-launcher#46]
(An option to) free up one slot in the dock by removing app drawer icon and adding a swipe-up action to reveal the app drawer.
This could simplify things even more.

**Comment by clemensbartz** [comment]
Thank you for the feedback.

That is really the long term plan for this one. But: Currently, I need this icon for the long press action. I thought about moving it to the drawer, but I have to see, how #40 will be implemented. I will keep you suggestion here when I am done.

**Comment by clemensbartz** [comment]
Implemented an on track for 1.6
