### ISSUE TITLE
Items disappear when scrolling fast in GridView

### ISSUE THREAD

**Issue by clemensbartz** [clemensbartz/essential-launcher#57]
Via mail by Emiliano:

### General Information

  * Essential Launcher Version: 1.6 (14)
  * Android Version: 6.0.1
  * Device with manufacturer: Samsung Galaxy S5 mini
  * App installed from: Play Store
  
### Actual behavior

When scrolling fast through the grid view entries, at some point in time, all items disappear.

### Expected behavior

When scrolling fast through the grid view entries, all items should be visible.

**Comment by clemensbartz** [comment]
Issue might be the `TextView`: [stackoverflow](https://stackoverflow.com/a/28762821)
> The problem with the height of TextView. So, make TextView single line like:
> `android:singleLine="true"`
> or, If u want 2 or 3 lines for some of the items, then make all the items have 2 or 3 lines like:
> `android:minLines="2"`

**Comment by esmoak** [comment]
If it helps, I had this issue in the previous version, so it isn't new to 1.6. It was hard to replicate so I didn't submit an issue.

**Comment by esmoak** [comment]
I cannot replicate the issue using list view on my device.

**Comment by clemensbartz** [comment]
Perfect. Thank you for trying. While reading through the web, also I also came across this post on [stackoverflow](https://stackoverflow.com/a/7624088) from 2011:

> I spoke with some of the boys at Google during the last Google Developer Lab and they told me that GridView is not maintained very much, and that I should use ListView, laying out the rows myself in code to make a grid.

I will try the first approach and see if it fixes the issue.

**Comment by clemensbartz** [comment]
Potential fix in 1.6.1. Please reopen if error persists.
