### ISSUE TITLE
Items in dock bounce when exiting app drawer with home button

### ISSUE THREAD

**Issue by esmoak** [clemensbartz/essential-launcher#58]
### General Information

  * Essential Launcher Version: 1.6
  * Android Version: 8.0.0
  * Device with manufacturer: Huawei Mate S3
  * RAM: 4gb
  * App installed from: F-Droid 
  
### Actual behavior

Access the app drawer. Press the android home button to exit the app drawer. The Essential icon and search icon at the top snap up quickly and my dock icons bounce up then back down to the normal position. If a widget is placed it bounces also.

### Expected behavior

A smooth transition with no bouncing.

**Comment by clemensbartz** [comment]
That bouncing is a “system bug” when hiding the Action Bar. It pulled the whole view to the top and upon hiding the bar the whole layout is readjusted. I will try to see if there is a fix for that.

**Comment by clemensbartz** [comment]
The "solution" is pretty much a hack, but unless it does not work out, here is how this will get implemented:

1. Set the action bar to floating in all themes, clip the content of the list views and adjust the toolbars accordingly.
2. Upon setting the theme, get the action bar height with [this code](https://gist.github.com/hamakn/8939eb68a920a6d7a498) (curtesy of hamakn).
3. Set the top padding of each list view to the height of the ActionBar.

**Comment by clemensbartz** [comment]
Issue is fixed in 1.6.1.
