### ISSUE TITLE
[Feature Request]: Add toggle to not count opened apps

### ISSUE THREAD

**Issue by late-latte** [clemensbartz/essential-launcher#59]
* Essential Launcher Version: 1.6.1
  * Android Version: 7.1
  * Device with manufacturer: Multiple
  * RAM: Varies
  * App installed from: F-Droid
  
Just want to ask if you can add a toggle to not count opened apps at all. Some of my devices are really old, like a Galaxy Note 1, and I'd like to squeeze as much processing power and data storage as possible, even if only a tiny bit. It'd also be great to keep icon placing on home from being switched around so much for those who'd like consistency.

**Comment by late-latte** [comment]
I could most definitely live with getting reacquainted with alphabetical sorting, but I think the UX of having it stickied with usage belies several notions that I think is incompatible with the spirit of being "essential":
1. Some people who'd prefer not having stickied apps at all on homescreen (in my relative's case, she'd prefer not to accidentally touch icons on home apps) would have to disable sticky one by one; and it can get grating if they've got many apps. To remedy this, the easiest fix probably would be a button to universally stop sticky.
2. Some people like me would prefer a certain ordering that may not necessarily aligned alphabetically. In my case, I'd like phone and a favorite chat app on the right side, because I'm right handed, and payment apps on the left. Those may not be the apps I most frequently use, but they're the apps I know I want to have quicker access to. Granted, I think people who wanted to sticky have had their own ideas what they're going to fill them with without the help of usage tracking anyway. So, also a button to stop usage tracking.
3. As aforementioned, it'll no doubt improve (however negligible) binary size and memory footprint. To some paranoid users (especially since this app is listed in F-Droid), not having usage tracking baked in would be extra boon.

I believe all three of them can be easily addressed by completely cutting out usage tracking and just allow users to assign x app to slot 1, y app to slot 2, etc,; but whatever direction you're going with, I'm gonna respect that and enjoy the ride with you. :)

**Comment by clemensbartz** [comment]
I am not sure how many people are actually using the tracking feature. However, I also see some privacy concerns when the phone becomes compromised.

Fixing icons in the dock might be a good solution which of course comes at the cost of removing the tracking feature. Otherwise, the size restrictions cannot be held.

**Comment by clemensbartz** [comment]
App tracking feature has been removed completely. Apps can now be pinned to individual positions.
