### ISSUE TITLE
app icon not showing

### ISSUE THREAD

**Issue by toto-1** [clemensbartz/essential-launcher#60]
### General Information

  * Essential Launcher Version: 2.0
  * Android Version: 8.1
  * Device with manufacturer:
  * RAM:
  * App installed from: F-Droid
  
### Actual behavior
Updating essential launcher from 1.6.1 to 2.0 leads to the last app icon in the list not being shown anymore.

### Expected behavior
Showing all app icons that are not hidden.

Going back to version 1.6.1 the app icon is shown again.

Best regards,
toto-1.

**Comment by clemensbartz** [comment]
Hello,

Thanks for reporting. Is that app by any chance the YouTube App?

**Comment by toto-1** [comment]
Hi,

no, it's Whatsapp.
(Newest version from whatsapp.com)

**Comment by clemensbartz** [comment]
Thank you. I confirmed with two other people as well. This is a bug.

**Comment by clemensbartz** [comment]
Will be fixed in 2.0.1.
