### ISSUE TITLE
Dock does not autopopulate with frequently used apps

### ISSUE THREAD

**Issue by Zuccace** [clemensbartz/essential-launcher#77]
### General Information

  * Essential Launcher Version: 2.2 (f-droid)
  * Android Version: 9
  * Device with manufacturer: Sony G8441/Lilac/Xperia XZ1 Compact
  * RAM: 4GB (around 2GB free on normal use)
  * App installed from: f-droid repository

  * neofetch:
```
$ neofetch --stdout
u0_a204@localhost
-----------------
OS: Android 9 aarch64
Host: Sony G8441
Kernel: 4.4.148-perf+
Uptime: 16 days, 22 hours, 23 mins
Packages: 142 (dpkg), 1 (pkg)
Shell: bash 5.0.11
CPU: Qualcomm MSM8998 (8) @ 1.900GHz
Memory: 1966MiB / 3728MiB
```
  
### Actual behavior
Dock does not autopopulate with frequently used apps.
Here I've pinned some apps but the two remaining slots don't ever get populated.
![Oh poo...](https://i.imgur.com/TXTSyAp.jpg)

### Expected behavior
The dock should autopopulate by itself with the most used/opened apps.

**Comment by Zuccace** [comment]
Wait? "enhancement"?
README states: 

> Dock with five frequently used applications.

I'm confused. Was this functionality removed lately?

**Comment by clemensbartz** [comment]
Your confusion is my fault, indeed, README is wrong. For my own reference: [website](https://clemensbartz.de/essential-launcher/index.html), Play Store, and f-droid are correct.

The tracking feature was removed with [version 2.0](https://github.com/clemensbartz/essential-launcher/releases/tag/v2.0) due to privacy concerns. I will update README shortly.

**Comment by clemensbartz** [comment]
README has been improved.

Due to size restrictions (50 KB max app size), I will not add that feature again, even not optionally.

**Comment by Zuccace** [comment]
Thanks. :) I'll then pin my dock full.
    -- Ilja Sara
