### ISSUE TITLE
Publish APK

### ISSUE THREAD

**Issue by IzzySoft** [clemensbartz/essential-launcher#9]
Are you planning to publish the `.apk`? A good idea would be to attach one to the corresponding `releases/` (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help if you're not familiar with the idea, it's easy to do).

**Comment by clemensbartz** [comment]
Yes, I can do that. Do you know if I should upload the signed (v1 or v2) `.apk`or just the plain release version?

**Comment by clemensbartz** [comment]
I have released the signed version of 1.3 in its corresponding tag. If there are any problems, feel free to reopen this issue.

**Comment by IzzySoft** [comment]
Superb, thanks Clemens! I've [included it with my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/de.clemensbartz.android.launcher), so folks preferring F-Droid over Playstore can now install it from there. Updates will be available within 24h of your creating a new tag and attaching an `.apk` to it.

If you want to, we could also bring your launcher into the official F-Droid repo; as far as I can see, it meets all their inclusion criteria. If you'd like that, let me know if you need assistance (I could file the "Request For Packaging" (RFP) for you. As F-Droid usually signs packages with their own key, other than with my repo cross-updates would not be possible – but on demand, they also offer "reproducible builds" (i.e. they build from your sources and compare the result with the `.apk` you provide; if the two match, *your* `.apk` is taken, so cross-updates are possible); so we should include with the RFP if you want that.

Meanwhile: thanks again – and congrats to a small but powerful app! APKs with less than 1MB size are becoming rarities, so yours is a special gem!

**Comment by clemensbartz** [comment]
That is also a good idea. I opened a new issue #10.
