### ISSUE TITLE
F-Droid - the privileged permissions have not been granted

### ISSUE THREAD

**Issue by Iskanderung** [clemensbartz/essential-launcher#91]
### General Information

  * Essential Launcher Version: latest
  * Android Version: 10
  * Device with manufacturer: Mediatek P10 (jlinksz)
  * RAM: 10 Gb
  * App installed from: Fdroid
  
### Actual behavior

 the privileged permissions have not been granted. Error in installation

**Comment by clemensbartz** [comment]
Thank you for reaching out. I would like to redirect you to the F-Droid maintainers. This issue is caused by F-Droid. Essential Launcher has not been run yet. 

There is a thread here which might be of help for you: https://forum.f-droid.org/t/privileged-installation-problems/5620
